name: poincare-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - torchaudio
  - scikit-learn
  - matplotlib
  - pillow
  - umap-learn
  - pip
  - pip:
      - tap.py
